name: Build Tai

on:
  push:
    branches: [ master, main, develop, feat/*, hotfix/* ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Restore NuGet packages
      run: |
        nuget restore Tai.sln
        
    - name: Build solution
      run: |
        msbuild Tai.sln /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal
        
    - name: Create artifacts directory
      run: |
        mkdir -p artifacts
        
    - name: Copy build outputs
      run: |
        xcopy /E /I /Y "UI\bin\Release\*" "artifacts\"
        xcopy /E /I /Y "Core\bin\Release\*" "artifacts\"
        xcopy /E /I /Y "TaiBug\bin\Release\*" "artifacts\"
        xcopy /E /I /Y "Updater\bin\Release\*" "artifacts\"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tai-build-artifacts
        path: artifacts/
        
    - name: Build summary
      run: |
        echo "Build completed successfully!"
        echo "Artifacts are available in the artifacts directory"
