name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Setup .NET Framework
      uses: microsoft/setup-dotnet@v3
      with:
        dotnet-version: '4.8.x'
        
    - name: Restore NuGet packages
      run: |
        nuget restore Tai.sln
        
    - name: Run tests
      run: |
        echo "Running tests..."
        # 这里可以添加单元测试命令
        echo "Tests completed"
        
    - name: Build solution
      run: |
        msbuild Tai.sln /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal
        
  deploy:
    needs: test
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Setup .NET Framework
      uses: microsoft/setup-dotnet@v3
      with:
        dotnet-version: '4.8.x'
        
    - name: Restore NuGet packages
      run: |
        nuget restore Tai.sln
        
    - name: Build for deployment
      run: |
        msbuild Tai.sln /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal
        
    - name: Create release package
      run: |
        mkdir -p release
        xcopy /E /I /Y "UI\bin\Release\*" "release\"
        xcopy /E /I /Y "Core\bin\Release\*" "release\"
        xcopy /E /I /Y "TaiBug\bin\Release\*" "release\"
        xcopy /E /I /Y "Updater\bin\Release\*" "release\"
        
    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tai-release
        path: release/
        retention-days: 30 